language: R
r:
  - release

warnings_are_errors: false

script:
  - echo "skipping_tests"

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'

addons:
  apt:
    packages:
      - libgit2-dev
